% Produced by CVXGEN, 2021-05-13 12:21:53 -0400.
% CVXGEN is Copyright (C) 2006-2017 Jacob Mattingley, jem@cvxgen.com.
% The code in this file is Copyright (C) 2006-2017 Jacob Mattingley.
% CVXGEN, or solvers produced by CVXGEN, cannot be used for commercial
% applications without prior written permission from Jacob Mattingley.

% Filename: cvxsolve.m.
% Description: Solution file, via cvx, for use with sample.m.
function [vars, status] = cvxsolve(params, settings)
A = params.A;
B = params.B;
Jacob = params.Jacob;
Jacob_limit = params.Jacob_limit;
P = params.P;
a_max = params.a_max;
adm_qdot = params.adm_qdot;
l = params.l;
opt_qdot_prev = params.opt_qdot_prev;
cvx_begin
  % Caution: automatically generated by cvxgen. May be incorrect.
  variable opt_qdot(8, 1);
  variable delta(6, 1);

  minimize(quad_form(opt_qdot - adm_qdot, eye(8)) + l*quad_form(delta, eye(6)));
  subject to
    P*Jacob_limit*opt_qdot == delta;
    A'*Jacob*opt_qdot <= B;
    -a_max <= opt_qdot - opt_qdot_prev;
    opt_qdot - opt_qdot_prev <= a_max;
cvx_end
vars.delta = delta;
vars.opt_qdot = opt_qdot;
status.cvx_status = cvx_status;
% Provide a drop-in replacement for csolve.
status.optval = cvx_optval;
status.converged = strcmp(cvx_status, 'Solved');
